# Generated by Django 5.2.6 on 2026-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
