# Generated by Django 5.2.6 on 2026-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customermodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
