# Generated by Django 5.2.6 on 2026-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profilemodel_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
