# Generated by Django 5.2.6 on 2026-04-06 14:35

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customermodel_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'managed': True, 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'managed': True, 'verbose_name': 'CustomerProfile', 'verbose_name_plural': 'CustomerProfiles'},
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='state',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='state_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='customermodel',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='profilemodel',
            table='customerprofile',
        ),
    ]
