# Generated by Django 5.2.6 on 2026-04-06 14:38

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address_line_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address_line_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='postal_code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='state_region',
            field=models.CharField(max_length=100),
        ),
    ]
