# Generated by Django 5.2.6 on 2026-05-25 12:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_profilemodel_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
