# Generated by Django 5.2.6 on 2025-12-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customusermodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
