# Generated by Django 5.2.6 on 2026-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customusermodel_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
