# Generated by Django 5.2.6 on 2026-05-27 15:52

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
