# Generated by Django 5.2.6 on 2026-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_sellermodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sellermodel',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
