# Generated by Django 5.2.6 on 2026-05-25 12:15

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellermodel_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='address_line_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='address_line_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='business_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='business_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='postal_code',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sellermodel',
            name='state_region',
            field=models.CharField(max_length=100),
        ),
    ]
