# Generated by Django 5.2.6 on 2026-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_sellermodel_created_at_sellermodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
